### ISSUE TITLE
eve-ng 5.0.1-13 

### ISSUE THREAD

**Issue by bayden10** [NikolayDachev/eve-ng#5]
EVE-NG v5.0.1-13 Community Edition

First export attempt on CHR 6.49.6 (existing configured CHR) indicates starting export but no prompt is given and does not complete. When trying to export same CHR on second attempt error is given - ERROR: "Failed to lock the lab (60061)."

**Comment by rogierbanis** [comment]
Same here with 6.48.6LT

**Comment by NikolayDachev** [comment]
> Same here with 6.48.6LT

Is the problem for 6.48.6LT is for the same version EVE-NG v5.0.1-13 Community Edition ?

Both reported issues are related only to export function ?
How the configuration was apply 

1. Manually added configuration 
2. CHR apply it on first boot 
3. problem happen when configuration was edited and export action fail 
OR
1. CHR without configuration 
2. Manually configured CHR 
3. export function fail ?

Regards

**Comment by NikolayDachev** [comment]
I found the problem,
For sure ros admin user password was set!
I will update the README with more information about the problem.

The short story: In order to export/import config the script (and I think this is valid for all eve-ng vm/os's ) script use telnet (console connection to the ros), however when password is set script cannot login in order to export/import 

For now please DO NOT set admin password, if you config the vm via console and see "new password" just press "ctl+c" or via windbox just ignore prompt for new password, also do not se password via import script!

The story is more complicated and is not related to the script ! 
How this can be solve is more related to eve-en - PHP code .. 

As I say, I will update the README with more details.

**Comment by rogierbanis** [comment]
Awesome, it works. Thanks!

Van: Nikolay Dachev ***@***.***>
Datum: zondag, 27 november 2022 om 20:16
Aan: NikolayDachev/eve-ng ***@***.***>
CC: Rogier Banis ***@***.***>, Comment ***@***.***>
Onderwerp: Re: [NikolayDachev/eve-ng] eve-ng 5.0.1-13 (Issue #5)

I found the problem,
I sure ros admin user password was set!
I will update the README with more information about the problem.
The short story: I order to export/import config the script (and I think this is valid for all eve-ng vm/os's ) script use telnet (console connection to the ros), however when password is set script cannot login in order to export/import

For now please DO NOT set admin password, if you config the vm via console and see "new password" just press "ctl+c" or via windbox just ignore prompt for new password, also do not se password via import script!

The story is more complicated and is not related to the script !
How this can be solve is more related to eve-en - PHP code ..

As I say, I will update the README with more details.

**Comment by NikolayDachev** [comment]
README notes are  update
